### ISSUE TITLE
make error. can't open file "drivers/net/wireless/ralink/mt76x3_ap/Kconfig.org"

### ISSUE THREAD

**Issue by vrichv** [trublemaker/mt7603-4.1.2.0#1]
make[1]: Entering directory '/home/xyz/work/padavan-ng/trunk/linux-3.4.x'
scripts/kconfig/conf --olddefconfig Kconfig
drivers/net/wireless/ralink/mt76x3_ap/Kconfig:423: can't open file "drivers/net/wireless/ralink/mt76x3_ap/Kconfig.org"
/home/xyz/work/padavan-ng/trunk/linux-3.4.x/scripts/kconfig/Makefile:85: recipe for target 'olddefconfig' failed

and this error.

In file included from drivers/net/wireless/ralink/mt76x3/include/rt_config.h:73,
                 from drivers/net/wireless/ralink/mt76x3_ap/../mt76x3/ap/ap.c:29:
drivers/net/wireless/ralink/mt76x3/include/rtmp.h:6812: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
scripts/Makefile.build:307: recipe for target 'drivers/net/wireless/ralink/mt76x3_ap/../mt76x3/ap/ap.o' failed
make[5]: *** [drivers/net/wireless/ralink/mt76x3_ap/../mt76x3/ap/ap.o] Error 1
scripts/Makefile.build:443: recipe for target 'drivers/net/wireless/ralink/mt76x3_ap' failed
make[4]: *** [drivers/net/wireless/ralink/mt76x3_ap] Error 2

**Comment by trublemaker** [comment]
it seems dir is not correct.
I make it use ln
rt-n56u/trunk/linux-3.4.x/drivers/net/wireless/ralink
mt76x3_ap ->  xxxx/76x3/mt76x3_ap
mt76x3 -> xxxx/76x3/mt76x3
and Kconfig.org is in the dir mt76x3_ap.
